# Generated by Django 4.1.7 on 2023-03-13 20:17

from django.db import migrations
from django.contrib.auth.models import Permission
from django.contrib.auth.management import create_permissions

def add_permissions(apps, schema_migration):
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, verbosity=0)
        app_config.models_module = None

def create_groups(apps, schema_migration):
    Group = apps.get_model('auth', 'Group')
   
    administrators = Group(name='administrators')
    administrators.save()
    all_permissions = Permission.objects.all()
    all_permissions_list = [permission.id for permission in all_permissions]
    administrators.permissions.add(*all_permissions_list)
    administrators.save()
    

    salers = Group(name='salers')
    salers.save()

    supporters = Group(name='supporters')
    supporters.save()

class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_permissions),
        migrations.RunPython(create_groups)
    ]
