# Generated by Django 4.1.7 on 2023-03-13 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.contrib.auth.management import create_permissions

def add_permissions(apps, schema_migration):
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, verbosity=0)
        app_config.models_module = None

def set_client_permissions_for_administrators(apps, schema_migration):
    Group = apps.get_model('auth', 'Group')
    administrators = Group.objects.get(name='administrators')
    salers = Group.objects.get(name='salers')

    Permission = apps.get_model('auth', 'Permission')

    add_client = Permission.objects.get(codename='add_client')
    change_client = Permission.objects.get(codename='change_client')
    delete_client = Permission.objects.get(codename='delete_client')
    view_client = Permission.objects.get(codename='view_client')

    administrators_permissions = [
        add_client,
        change_client,
        delete_client,
        view_client,
    ]
    all_permissions_list = [permission.id for permission in administrators_permissions]
    administrators.permissions.add(*all_permissions_list)
    administrators.save()

    salers.permissions.add(add_client)
    salers.permissions.add(view_client)
    salers.save()

class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20230313_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=25, null=True)),
                ('last_name', models.CharField(blank=True, max_length=25, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('company_name', models.CharField(max_length=250)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_client', models.BooleanField(default=False)),
                ('sales_contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(add_permissions),
        migrations.RunPython(set_client_permissions_for_administrators)
    ]
