# Generated by Django 4.1.7 on 2023-03-14 10:30

from django.db import migrations
from django.contrib.auth.hashers import make_password

def add_first_user(apps, schema_migration):
    user = apps.get_model('application', 'User')
    first_user = user.objects.create(
        username = 'admin',
        first_name = 'first',
        last_name = 'administrators',
        email = 'administrators@test.co',
        is_staff = True)
    first_user.password = make_password('1234')
    first_user.save()

    group = apps.get_model('auth', 'Group')
    administrators = group.objects.get(name='administrators')
    administrators.user_set.add(first_user)

class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_client'),
    ]

    operations = [
        migrations.RunPython(add_first_user)
    ]
