# Generated by Django 4.1.7 on 2023-03-14 15:55

import application.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.contrib.auth.management import create_permissions

def add_permissions(apps, schema_migration):
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, verbosity=0)
        app_config.models_module = None

def set_contract_permissions_for_administrators(apps, schema_migration):
    Group = apps.get_model('auth', 'Group')
    administrators = Group.objects.get(name='administrators')
    salers = Group.objects.get(name='salers')

    Permission = apps.get_model('auth', 'Permission')

    add_contract = Permission.objects.get(codename='add_contract')
    change_contract = Permission.objects.get(codename='change_contract')
    delete_contract = Permission.objects.get(codename='delete_contract')
    view_contract = Permission.objects.get(codename='view_contract')

    administrators_permissions = [
        add_contract,
        change_contract,
        delete_contract,
        view_contract,
    ]
    all_permissions_list = [permission.id for permission in administrators_permissions]
    administrators.permissions.add(*all_permissions_list)
    administrators.save()

    salers.permissions.add(add_contract)
    salers.permissions.add(view_contract)
    salers.save()

class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_add_first_admin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='sales_contact',
            field=models.ForeignKey(limit_choices_to=application.models.limit_users_sales_contact, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('payment_due', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(limit_choices_to={'is_client': 'True'}, on_delete=django.db.models.deletion.CASCADE, to='application.client')),
                ('sales_contact', models.ForeignKey(limit_choices_to=application.models.limit_users_sales_contact, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(add_permissions),
        migrations.RunPython(set_contract_permissions_for_administrators)
    ]
